version: '3.8'

networks:
  kstar_network:
    driver: bridge
    enable_ipv6: false

services:

  kstart-account-management:
    container_name: kstart-account-management
    build: .
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
      - 5173:5173
    networks:
      - kstar_network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: minkhant
      POSTGRES_PASSWORD: min293822
      POSTGRES_DB: kstar_account_management_db
    ports:
      - 5432:5432
    networks:
      - kstar_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mkt23822@gmail.com
      PGADMIN_DEFAULT_PASSWORD: min293822
    ports:
      - 9001:80
    depends_on:
      - postgres_db
    networks:
      - kstar_network
