version: '3.8'

networks:
  kstar_network:
    driver: bridge
    enable_ipv6: false

services:

  kstart-account-management:
    image: minkhant123/k-star-account-management:0.1
    container_name: kstart-account-management
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 8000:80
      - 5173:5173
    networks:
      - kstar_network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - kstar_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mkt23822@gmail.com
      PGADMIN_DEFAULT_PASSWORD: min293822
    ports:
      - 9001:80
    depends_on:
      - postgres_db
    networks:
      - kstar_network
